version: "3"

services:
  go-exec:
    build:
      context: ../docker/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ../../src:/go/src/app/
      
  redis:
    image: redis:7.0.7-alpine3.17

